version: "3.1"

services:
  postgres:
    image: postgres:13.3-alpine
    restart: always
    env_file: .env.local
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  postgres:
